### PR TITLE
Done translation for guide

### PR DESCRIPTION
**Pull request by superyusuke**
This is in progress. 

But I have some question and write directly on .mdx with 'nakanish' comment. Like this:

screen shot 2019-03-01 at 21 07 45

So please explain that.

### CODE REVIEW

**Comment by jamesknelson** [comment]
Thanks for your translation! I've edited the paragraph with your questions. I hope that it is clearer now.

> Similarly, if `<View />` finds that `getView()` or `getData()` have failed, then the `View` component will throw an error. In fact, if the router encounters a 404-not-found error, then `<View />` will throw that, too. These errors can be caught by [Error Boundary](https://reactjs.org/docs/error-boundaries.html) components. For the most part, you'll need to make your own error boundaries, but Navi includes a `<NotFoundBoundary>` that can catch Not Found errors for you and show a fallback message instead:

Please let me know if you have any more questions.

**Comment by superyusuke** [comment]
Thanks! fix that.
The rest is 2 bock ...

**Comment by superyusuke** [comment]
@jamesknelson 
All done but still one question left.
Please check it.

**Comment by jamesknelson** [comment]
Yes, your understand looks correct. Thanks!

**Comment by superyusuke** [comment]
Thanks. All done.

**Comment by superyusuke** [comment]
Could you tell me if there is anything that concerns you?

**Comment by jamesknelson** [comment]
I think it is OK, I'd just like to double check it before merging in. I haven't had time yet, but will try to do so later today.

**Comment by jamesknelson** [comment]
Thankyou, I'll deploy this later today!

**Pull request merged**
